package com.example.demo.config;

import lombok.Getter;

@Getter
public enum Status { ACTIVATED, DELETED ,BIDDING, PROCEEDING, COMPLETED, CANCELED,EXPIRED, BEFORE_PAYMENT, PAYMENT_COMPLETED,WAITING,SENT, INCOMING, UNDER_INSPECTION, INSPECTION_COMPLETED,SHIPPING, DELIVERY_COMPLETED, PAYMENT_SUCCESS, PAYMENT_FAIL,REGISTERING;
}